// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Step struct {
	ID           string          `json:"id"`
	TraceID      string          `json:"trace_id"`
	ParentStepID sql.NullString  `json:"parent_step_id"`
	StepName     string          `json:"step_name"`
	Status       string          `json:"status"`
	Input        json.RawMessage `json:"input"`
	Output       json.RawMessage `json:"output"`
	Reasoning    sql.NullString  `json:"reasoning"`
	StartedAt    time.Time       `json:"started_at"`
	EndedAt      sql.NullTime    `json:"ended_at"`
	OrderIndex   int64           `json:"order_index"`
}

type Trace struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	StartedAt   time.Time       `json:"started_at"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	Status      string          `json:"status"`
	Metadata    json.RawMessage `json:"metadata"`
}
